### ISSUE TITLE
error in check_password

### ISSUE THREAD

**Issue by foreignperson** [miguelgrinberg/microblog#142]
Hi, when i'm trying to login, the browser returns me 

> 500 Internal Server Error
> The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

and the terminal:

```
[2019-01-04 00:22:17,526] ERROR in app: Exception on /login [POST]
Traceback (most recent call last):
  File "/home/fperson/.local/share/virtualenvs/microblog-Icx_SaKb/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/fperson/.local/share/virtualenvs/microblog-Icx_SaKb/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/fperson/.local/share/virtualenvs/microblog-Icx_SaKb/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/fperson/.local/share/virtualenvs/microblog-Icx_SaKb/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/fperson/.local/share/virtualenvs/microblog-Icx_SaKb/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/fperson/.local/share/virtualenvs/microblog-Icx_SaKb/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/fperson/learning/flask_mega-tutorial_habr/microblog/app/routes.py", line 32, in login
    if user is None or not user.check_password(form.password.data):
  File "/home/fperson/learning/flask_mega-tutorial_habr/microblog/app/models.py", line 17, in check_password
    return check_password_hash(self.password_hash, password)
  File "/home/fperson/.local/share/virtualenvs/microblog-Icx_SaKb/lib/python3.6/site-packages/werkzeug/security.py", line 245, in check_password_hash
    if pwhash.count('$') < 2:
AttributeError: 'String' object has no attribute 'count'
```
error seems to be in werkzeug package. i tried to reinstall it, but it doesn't help.

routes.py:

```
# -*- coding: utf-8 -*- 
from app import app
from flask import render_template, flash, redirect, url_for
from app.forms import LoginForm
from app.models import User
from flask_login import logout_user, current_user, login_user, login_required

@app.route('/')
@app.route('/index')
@login_required

def index():
	posts=[
	{
		'author': {'username': 'John'},
		'body': 'Beautiful day in Poland!'
	},
	{
		'author': {'username': 'Naomi'},
		'body': 'It rains in London.'
	}]

	return render_template('index.html', title='Home', user=user, posts=posts)

@app.route('/login', methods=['GET', 'POST'])
def login():
	if current_user.is_authenticated:
		return redirect(url_for('index'))
	form=LoginForm()
	if form.validate_on_submit():
		user = User.query.filter_by(username=form.username.data).first()
		if user is None or not user.check_password(form.password.data):
			flash('Invalid username or password')
			return redirect(url_for('login'))
		login_user(user, remember=form.remember_me.data)
		next_page = request.args.get('next')
		if not next_page or url_parse(next_page).netloc !='':
			next_page = url_for('index')
		return redirect(next_page)

	return render_template('login.html', title='Sign In', form=form)

@app.route('/logout')
def logout():
	logout_user()
	return redirect(url_for('index'))
```

models.py:

```
from app import db, login
from datetime import datetime
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import UserMixin

class User(UserMixin, db.Model):
	id = db.Column(db.Integer, primary_key=True)
	username = db.Column(db.String(64), index=True, unique=True)
	email = db.Column(db.String(64), index=True, unique=True)
	password_hash = db.String(164)
	posts = db.relationship('Post', backref='author', lazy='dynamic')

	def set_password(self, password):
		self.password_hash = generate_password_hash(password)

	def check_password(self, password):
		return check_password_hash(self.password_hash, password)

	def __repr__(self):
		return '<User {}>'.format(self.username)
		

class Post(db.Model):
	id = db.Column(db.Integer, primary_key=True)
	body = db.Column(db.String(140))
	timestamp = db.Column(db.DateTime, index=True, default=datetime.utcnow)
	iser_id = db.Column(db.Integer, db.ForeignKey('user.id'))

	def __repr__(self):
		return '<Post {}>'.format(self.body)

@login.user_loader
def load_user(id):
	return User.query.get(int(id))
```

thank you.

**Comment by miguelgrinberg** [comment]
What do you have stored in the `password_hash` column? The error suggests you do not have a hash in there.

**Comment by foreignperson** [comment]
i think that the reason of the error is this line:
`password_hash = db.String(164)`

werkzeug tries to use python's str's functions to the String type. but when i write 
```
def check_password(self, password):
		return check_password_hash(str(self.password_hash), password)
```
it doesn't crush, but can't check, if i write right username and password it says that they'are not right.

**Comment by foreignperson** [comment]
oh, it was because i wrote `password_hash = db.String(164)`, now i've fixed it, but there's another error. it now says 
```
  File "/home/fperson/learning/flask_mega-tutorial_habr/microblog/app/routes.py", line 32, in login
    if user is None or not user.check_password(form.password.data):
  File "/home/fperson/learning/flask_mega-tutorial_habr/microblog/app/models.py", line 17, in check_password
    return check_password_hash(self.password_hash, password)
  File "/home/fperson/.local/share/virtualenvs/microblog-Icx_SaKb/lib/python3.6/site-packages/werkzeug/security.py", line 245, in check_password_hash
    if pwhash.count('$') < 2:
AttributeError: 'NoneType' object has no attribute 'count'
```

**Comment by miguelgrinberg** [comment]
@foreignperson you did not fix this problem correctly. Set `password_hash` to a `db.Column` object like all your other attributes, then migrate or regenerate your database, because by now you must have one or more users in there that have a bad password hash stored.

**Comment by foreignperson** [comment]
i wrote `password_hash = db.Column(db.String(128))`, but it still crushed, then i've deleted all users and added new one, and also fixed a small issue in routes.py. now it works, thank you!

**Comment by erhoneyraj2016** [comment]
@miguelgrinberg 
did whatever you are saying but still facing the same error.

<console>:1: SAWarning: DELETE statement on table 'user' expected to delete 2 row(s); 0 were matched.  Please set confirm_deleted_rows=False within the mapper configuration to prevent this warning.

**Comment by miguelgrinberg** [comment]
@erhoneyraj2016 I don't know what made you decide your issue matches the one discussed above. Note that this issue board is for the Flask Mega-Tutorial project. You seem to be working on something different, of which I know nothing. I recommend you ask your question on Stack Overflow and provide additional details.
